### ISSUE TITLE
FactoryBot/CreateList is crashing out with "undefined method 'to_sym' for nil"

### ISSUE THREAD

**Issue by geoffswift** [rubocop/rubocop-factory_bot#147]
When upgrading `rubocop-factory_bot` from 2.26.1 to 2.27.0 I am seeing a regression whereby rubocop crashes.

I'm using `rubocop-airbnb` so can't tell you much about how the rule is set up there.  Not sure where to start diagnosing this, but happy to respond to any questions / check things...

The callstack when I use `rubocop -d` looks like this
```
undefined method 'to_sym' for nil
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/mixin/configurable_enforced_style.rb:81:in 'RuboCop::Cop::ConfigurableEnforcedStyle#style'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-factory_bot-2.27.0/lib/rubocop/cop/factory_bot/create_list.rb:124:in 'RuboCop::Cop::FactoryBot::CreateList#on_block'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:107:in 'Kernel#public_send'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:107:in 'block (2 levels) in RuboCop::Cop::Commissioner#trigger_responding_cops'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:171:in 'RuboCop::Cop::Commissioner#with_cop_error_handling'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:106:in 'block in RuboCop::Cop::Commissioner#trigger_responding_cops'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:105:in 'Array#each'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:105:in 'RuboCop::Cop::Commissioner#trigger_responding_cops'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:69:in 'RuboCop::Cop::Commissioner#on_block'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:137:in 'block in RuboCop::AST::Traversal#on_dstr'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:137:in 'Array#each'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:137:in 'RuboCop::AST::Traversal#on_dstr'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_begin'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:158:in 'RuboCop::AST::Traversal#on_block'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_block'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:137:in 'block in RuboCop::AST::Traversal#on_dstr'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:137:in 'Array#each'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:137:in 'RuboCop::AST::Traversal#on_dstr'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_begin'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-ast-1.38.1/lib/rubocop/ast/traversal.rb:20:in 'RuboCop::AST::Traversal#walk'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/commissioner.rb:87:in 'RuboCop::Cop::Commissioner#investigate'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/team.rb:174:in 'RuboCop::Cop::Team#investigate_partial'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cop/team.rb:108:in 'RuboCop::Cop::Team#investigate'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:348:in 'block in RuboCop::Runner#inspect_file'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:347:in 'Array#each'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:347:in 'Enumerable#flat_map'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:347:in 'RuboCop::Runner#inspect_file'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:290:in 'block in RuboCop::Runner#do_inspection_loop'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:324:in 'block in RuboCop::Runner#iterate_until_no_changes'
<internal:kernel>:168:in 'Kernel#loop'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:317:in 'RuboCop::Runner#iterate_until_no_changes'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:286:in 'RuboCop::Runner#do_inspection_loop'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:167:in 'block in RuboCop::Runner#file_offenses'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:192:in 'RuboCop::Runner#file_offense_cache'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:166:in 'RuboCop::Runner#file_offenses'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:154:in 'RuboCop::Runner#process_file'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:135:in 'block in RuboCop::Runner#each_inspected_file'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:134:in 'Array#each'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:134:in 'Enumerable#reduce'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:134:in 'RuboCop::Runner#each_inspected_file'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:120:in 'RuboCop::Runner#inspect_files'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/runner.rb:73:in 'RuboCop::Runner#run'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli/command/execute_runner.rb:26:in 'block in RuboCop::CLI::Command::ExecuteRunner#execute_runner'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli/command/execute_runner.rb:52:in 'RuboCop::CLI::Command::ExecuteRunner#with_redirect'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli/command/execute_runner.rb:25:in 'RuboCop::CLI::Command::ExecuteRunner#execute_runner'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli/command/execute_runner.rb:17:in 'RuboCop::CLI::Command::ExecuteRunner#run'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli/command.rb:11:in 'RuboCop::CLI::Command.run'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli/environment.rb:18:in 'RuboCop::CLI::Environment#run'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli.rb:122:in 'RuboCop::CLI#run_command'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli.rb:129:in 'RuboCop::CLI#execute_runners'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli.rb:51:in 'block in RuboCop::CLI#run'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli.rb:81:in 'RuboCop::CLI#profile_if_needed'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/lib/rubocop/cli.rb:43:in 'RuboCop::CLI#run'
/usr/local/rvm/gems/ruby-3.4.1/gems/rubocop-1.73.2/exe/rubocop:19:in '<top (required)>'
/usr/local/rvm/gems/ruby-3.4.1/bin/rubocop:25:in 'Kernel#load'
/usr/local/rvm/gems/ruby-3.4.1/bin/rubocop:25:in '<main>'
/usr/local/rvm/gems/ruby-3.4.1/bin/ruby_executable_hooks:22:in 'Kernel#eval'
/usr/local/rvm/gems/ruby-3.4.1/bin/ruby_executable_hooks:22:in '<main>'
```

**Comment by geoffswift** [comment]
Disabling the rule `FactoryBot/CreateList`  solves the problem.  Noticed at the end of the failed run it says

```
Mention the following information in the issue report:
1.73.2 (using Parser 3.3.7.1, rubocop-ast 1.38.1, analyzing as Ruby 3.4, running on ruby 3.4.1) [arm64-darwin24]
```

**Comment by mockdeep** [comment]
I had the same issue. Updating the `rubocop-rspec` gem to `3.5.0` fixed it for me.
